apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-interview-1
spec:
  selector:
    matchLabels:
      app: devops-interview-1
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-interview-1
    spec:
      containers:
        - name: devops-interview-1
          image: "033069444749.dkr.ecr.us-east-1.amazonaws.com/devops-interview-1"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MESSAGE
              value: "Hello world!"