
   
apiVersion: v1
kind: Service
metadata:
  name: 'devops-interview-1-service'
  labels:
    name: 'devops-interview-1-service'
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: 'devops-interview-1'
  type: ClusterIP